algoritmo "nome e idade"
// Função : mostrar o nome e a idade do individuo
// Autor :
// Data : 18/05/2023
// Seção de Declarações 
var

idade:inteiro
nome:caracter

inicio
// Seção de Comandos

escreval ("seu nome")
leia (nome)

escreval ("sua idade")
leia (idade)

se (idade >= 18) entao
   escreval (nome, ", você é maior de idade")
   
senao
     escreval (nome, ", você é menor de idade")
     
fimse

fimalgoritmo
