Algoritmo "Atividade PA 2"
// Disciplina   :PA
// Professor   : 
// Aluno(a)    : iago s menezes
// Data atual  : 09/03/2023
Var
altura,base,perimetro,area:real
Inicio
escreval("Determine a altura do seu retângulo:")
leia(altura)
escreval("Determina a base do seu retângulo:")
leia(base)
area <- base*altura
perimetro <- altura+altura+base+base
escreval("O perimetro do seu retângulo é de ",perimetro," cm")
escreval("A area do seu retângulo é de ",area," cm")
Fimalgoritmo
